In [4]:
# first things first:
# check no 2 nodes with the same lines in the same group

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/Hubs_groups_with_full_data_flat.csv', encoding='windows-1255')

In [7]:
df.head(3)

,Column1,h3_index,node,Mode_Planned,Line_Nunique,Line_Unique,LandOwnership,Region,Location,Boardings_Daily,Alightings_Daily,TotalDemand_Daily,geometry,group,address
0,0,8a2da4100a27fff,31655,HighSpeed Rail,2,['rail_1_1' 'rail_1_2'],State,Haifa,Outer,2889.817785,147.867556,3037.685341,"POLYGON ((35.58265301880704 33.2100839260914, ...",0,"מנחם בגין/נורית, שדרות מנחם בגין, הורדים, קרית..."
1,1,8a2da4c22257fff,36963,BRT,1,['brt022'],State,Haifa,Outer,289.4615591,631.0450865,920.506646,"POLYGON ((35.32671223620188 32.92554871232436,...",1,"מיי סנטר, מעלה כמון, אזור תעשייה כרמיאל, כרמיא..."
2,2,8a2da4c22627fff,36959,BRT,1,['brt021'],State,Haifa,Outer,0,0.56331008,0.563310,POLYGON ((35.31703160566268 32.922357121183495...,2,"החרושת/חשמל, החרושת, אזור תעשייה כרמיאל, כרמיא..."

In [8]:
df.set_index('Column1', inplace=True)

In [24]:
suspected_nodes = {g:[] for g in df['group'].unique()}

In [25]:
for group, nodes in df.groupby('group')['node']:
  node_list = nodes.tolist()
  print(f'Group: {group}, Nodes: {node_list}')
  if len(node_list) == 1:
    continue
  for i, node_a in enumerate(node_list):
    for node_b in node_list[i+1:]:
      if set(df[df['node']==node_a]['Line_Unique'].to_list()) == set(df[df['node']==node_b]['Line_Unique'].to_list()):
        suspected_nodes[group].append(node_a)
        suspected_nodes[group].append(node_b)

Group: 0, Nodes: [31655]
Group: 1, Nodes: [36963]
Group: 2, Nodes: [36959, 36961]
Group: 3, Nodes: [36924]
Group: 4, Nodes: [36935]
Group: 5, Nodes: [36940]
Group: 6, Nodes: [36938]
Group: 7, Nodes: [36716]
Group: 8, Nodes: [36714]
Group: 9, Nodes: [36953]
Group: 10, Nodes: [31656, 31656]
Group: 11, Nodes: [36948]
Group: 12, Nodes: [36950]
Group: 13, Nodes: [36946]
Group: 14, Nodes: [36958]
Group: 15, Nodes: [36955]
Group: 16, Nodes: [36951]
Group: 17, Nodes: [36903, 30003, 36904]
Group: 18, Nodes: [36944]
Group: 19, Nodes: [36942]
Group: 20, Nodes: [36932]
Group: 21, Nodes: [31624, 31624]
Group: 22, Nodes: [36926]
Group: 23, Nodes: [36927]
Group: 24, Nodes: [36917]
Group: 25, Nodes: [36920]
Group: 26, Nodes: [36921]
Group: 27, Nodes: [36907, 30034, 36909]
Group: 28, Nodes: [36906]
Group: 29, Nodes: [36900]
Group: 30, Nodes: [36915]
Group: 31, Nodes: [36913]
Group: 32, Nodes: [36912]
Group: 33, Nodes: [34044]
Group: 34, Nodes: [34028]
Group: 35, Nodes: [34033]
Group: 36, Nodes: [34027]
Group: 37, Nodes: [34026]
Group: 38, Nodes: [36987, 34034, 35023, 36964, 36965]
Group: 39, Nodes: [36990]
Group: 40, Nodes: [34030]
Group: 41, Nodes: [34029]
Group: 42, Nodes: [34031]
Group: 43, Nodes: [34032]
Group: 44, Nodes: [36809]
Group: 45, Nodes: [36807]
Group: 46, Nodes: [19226]
Group: 47, Nodes: [36999]
Group: 48, Nodes: [36997]
Group: 49, Nodes: [36993]
Group: 50, Nodes: [36991]
Group: 51, Nodes: [36814]
Group: 52, Nodes: [36815]
Group: 53, Nodes: [36817]
Group: 54, Nodes: [36812]
Group: 55, Nodes: [34066]
Group: 56, Nodes: [34067]
Group: 57, Nodes: [34068]
Group: 58, Nodes: [44103]
Group: 59, Nodes: [44102]
Group: 60, Nodes: [36872]
Group: 61, Nodes: [44407]
Group: 62, Nodes: [44071]
Group: 63, Nodes: [36870]
Group: 64, Nodes: [44070]
Group: 65, Nodes: [34056]
Group: 66, Nodes: [34054]
Group: 67, Nodes: [34051, 1006]
Group: 68, Nodes: [1000, 34014, 36850]
Group: 69, Nodes: [49021]
Group: 70, Nodes: [36854]
Group: 71, Nodes: [1001]
Group: 72, Nodes: [34057]
Group: 73, Nodes: [34071, 31525, 31525]
Group: 74, Nodes: [34069]
Group: 75, Nodes: [34020]
Group: 76, Nodes: [34022]
Group: 77, Nodes: [36886]
Group: 78, Nodes: [43364]
Group: 79, Nodes: [36896]
Group: 80, Nodes: [36930]
Group: 81, Nodes: [36894]
Group: 82, Nodes: [36892]
Group: 83, Nodes: [36898]
Group: 84, Nodes: [36888]
Group: 85, Nodes: [36890]
Group: 86, Nodes: [36879]
Group: 87, Nodes: [36881]
Group: 88, Nodes: [34018]
Group: 89, Nodes: [34015]
Group: 90, Nodes: [34064, 36860, 34063, 36862, 36858]
Group: 91, Nodes: [44072]
Group: 92, Nodes: [988318]
Group: 93, Nodes: [467825]
Group: 94, Nodes: [467906]
Group: 95, Nodes: [467827]
Group: 96, Nodes: [467884]
Group: 97, Nodes: [467907]
Group: 98, Nodes: [467822]
Group: 99, Nodes: [467824]
Group: 100, Nodes: [467948]
Group: 101, Nodes: [467248]
Group: 102, Nodes: [467940]
Group: 103, Nodes: [467194]
Group: 104, Nodes: [467819]
Group: 105, Nodes: [467944]
Group: 106, Nodes: [467197, 463640, 463640, 463640]
Group: 107, Nodes: [467943]
Group: 108, Nodes: [467205]
Group: 109, Nodes: [467909]
Group: 110, Nodes: [467821]
Group: 111, Nodes: [467211, 463642, 463642, 463642]
Group: 112, Nodes: [467208]
Group: 113, Nodes: [467941]
Group: 114, Nodes: [467199]
Group: 115, Nodes: [467202]
Group: 116, Nodes: [467750]
Group: 117, Nodes: [467867]
Group: 118, Nodes: [467818]
Group: 119, Nodes: [467811]
Group: 120, Nodes: [467249]
Group: 121, Nodes: [467192]
Group: 122, Nodes: [467763]
Group: 123, Nodes: [467761]
Group: 124, Nodes: [467765]
Group: 125, Nodes: [467758]
Group: 126, Nodes: [467759]
Group: 127, Nodes: [467764]
Group: 128, Nodes: [467767]
Group: 129, Nodes: [467756]
Group: 130, Nodes: [467926]
Group: 131, Nodes: [467928]
Group: 132, Nodes: [467927]
Group: 133, Nodes: [467755]
Group: 134, Nodes: [463793, 467925]
Group: 135, Nodes: [467942]
Group: 136, Nodes: [467829]
Group: 137, Nodes: [467950]
Group: 138, Nodes: [467893]
Group: 139, Nodes: [467932]
Group: 140, Nodes: [467933]
Group: 141, Nodes: [467934]
Group: 142, Nodes: [463984]
Group: 143, Nodes: [467949]
Group: 144, Nodes: [467947]
Group: 145, Nodes: [463799]
Group: 146, Nodes: [467794]
Group: 147, Nodes: [467791]
Group: 148, Nodes: [467805]
Group: 149, Nodes: [467808]
Group: 150, Nodes: [467836]
Group: 151, Nodes: [467807]
Group: 152, Nodes: [467251]
Group: 153, Nodes: [988494]
Group: 154, Nodes: [467180]
Group: 155, Nodes: [467250]
Group: 156, Nodes: [512087]
Group: 157, Nodes: [512100, 500109]
Group: 158, Nodes: [500210]
Group: 159, Nodes: [512156]
Group: 160, Nodes: [512155]
Group: 161, Nodes: [500211]
Group: 162, Nodes: [512157]
Group: 163, Nodes: [512148]
Group: 164, Nodes: [500093, 282738, 500094]
Group: 165, Nodes: [512178]
Group: 166, Nodes: [512179]
Group: 167, Nodes: [512177, 500097]
Group: 168, Nodes: [512276, 512275]
Group: 169, Nodes: [282739, 500096]
Group: 170, Nodes: [282737, 500095]
Group: 171, Nodes: [512164]
Group: 172, Nodes: [500049]
Group: 173, Nodes: [500193, 512094]
Group: 174, Nodes: [500208]
Group: 175, Nodes: [500209]
Group: 176, Nodes: [512088]
Group: 177, Nodes: [512214]
Group: 178, Nodes: [512280]
Group: 179, Nodes: [512279]
Group: 180, Nodes: [512213]
Group: 181, Nodes: [512167]
Group: 182, Nodes: [500091]
Group: 183, Nodes: [500092, 512089]
Group: 184, Nodes: [512077]
Group: 185, Nodes: [512133]
Group: 186, Nodes: [500100]
Group: 187, Nodes: [512288]
Group: 188, Nodes: [500099]
Group: 189, Nodes: [500073, 500212, 500072]
Group: 190, Nodes: [512278]
Group: 191, Nodes: [500098]
Group: 192, Nodes: [512175]
Group: 193, Nodes: [400841, 400841]
Group: 194, Nodes: [500089]
Group: 195, Nodes: [500090]
Group: 196, Nodes: [512284]
Group: 197, Nodes: [500206]
Group: 198, Nodes: [500207]
Group: 199, Nodes: [512285]
Group: 200, Nodes: [512281]
Group: 201, Nodes: [500188, 512166]
Group: 202, Nodes: [512282]
Group: 203, Nodes: [512163]
Group: 204, Nodes: [512283]
Group: 205, Nodes: [512149]
Group: 206, Nodes: [500205]
Group: 207, Nodes: [512165]
Group: 208, Nodes: [500087, 500086]
Group: 209, Nodes: [500088]
Group: 210, Nodes: [500070]
Group: 211, Nodes: [500071]
Group: 212, Nodes: [500066]
Group: 213, Nodes: [512120]
Group: 214, Nodes: [512181]
Group: 215, Nodes: [512180]
Group: 216, Nodes: [512095]
Group: 217, Nodes: [512289]
Group: 218, Nodes: [512184]
Group: 219, Nodes: [512078]
Group: 220, Nodes: [512183]
Group: 221, Nodes: [512274]
Group: 222, Nodes: [511085]
Group: 223, Nodes: [511047]
Group: 224, Nodes: [511056]
Group: 225, Nodes: [500218]
Group: 226, Nodes: [500217]
Group: 227, Nodes: [500219]
Group: 228, Nodes: [500220]
Group: 229, Nodes: [500221]
Group: 230, Nodes: [500064]
Group: 231, Nodes: [500065]
Group: 232, Nodes: [500063]
Group: 233, Nodes: [500033]
Group: 234, Nodes: [500238]
Group: 235, Nodes: [500233]
Group: 236, Nodes: [500035]
Group: 237, Nodes: [500034]
Group: 238, Nodes: [500027, 500225]
Group: 239, Nodes: [500237]
Group: 240, Nodes: [500216]
Group: 241, Nodes: [500214, 500047]
Group: 242, Nodes: [500046, 500045]
Group: 243, Nodes: [500215]
Group: 244, Nodes: [500222, 500042, 400820, 400820]
Group: 245, Nodes: [500032]
Group: 246, Nodes: [500044]
Group: 247, Nodes: [500043]
Group: 248, Nodes: [500031]
Group: 249, Nodes: [500223]
Group: 250, Nodes: [500224]
Group: 251, Nodes: [525472]
Group: 252, Nodes: [525473]
Group: 253, Nodes: [260147]
Group: 254, Nodes: [525469]
Group: 255, Nodes: [265017, 525470]
Group: 256, Nodes: [511081]
Group: 257, Nodes: [511080]
Group: 258, Nodes: [511084]
Group: 259, Nodes: [525480]
Group: 260, Nodes: [511046, 525481]
Group: 261, Nodes: [525482]
Group: 262, Nodes: [511083]
Group: 263, Nodes: [511045]
Group: 264, Nodes: [511082]
Group: 265, Nodes: [511044]
Group: 266, Nodes: [511079]
Group: 267, Nodes: [511043]
Group: 268, Nodes: [511078]
Group: 269, Nodes: [525483]
Group: 270, Nodes: [525484]
Group: 271, Nodes: [511049, 512132, 512185, 511109]
Group: 272, Nodes: [511108]
Group: 273, Nodes: [511071, 512190]
Group: 274, Nodes: [511094, 512147]
Group: 275, Nodes: [511058]
Group: 276, Nodes: [511059, 400380, 400380, 511050, 512134]
Group: 277, Nodes: [511070, 511088, 512121, 511089, 512122]
Group: 278, Nodes: [525475]
Group: 279, Nodes: [525476]
Group: 280, Nodes: [512195, 511087, 512270, 525477, 511086, 525478]
Group: 281, Nodes: [511090, 512193]
Group: 282, Nodes: [525474]
Group: 283, Nodes: [525479, 512269]
Group: 284, Nodes: [511104]
Group: 285, Nodes: [511103]
Group: 286, Nodes: [511106]
Group: 287, Nodes: [511105]
Group: 288, Nodes: [511107]
Group: 289, Nodes: [512286, 511048, 512105]
Group: 290, Nodes: [511092, 512124]
Group: 291, Nodes: [511101]
Group: 292, Nodes: [511102]
Group: 293, Nodes: [511069, 512123]
Group: 294, Nodes: [511091, 512192]
Group: 295, Nodes: [511093, 512097]
Group: 296, Nodes: [525471]
Group: 297, Nodes: [512273]
Group: 298, Nodes: [512272]
Group: 299, Nodes: [512146, 511067]
Group: 300, Nodes: [511277]
Group: 301, Nodes: [512073, 511099, 511051, 511100, 511110, 512082, 511055, 512231, 400360, 400360]
Group: 302, Nodes: [512237, 511097, 512238, 511098]
Group: 303, Nodes: [512108]
Group: 304, Nodes: [512118]
Group: 305, Nodes: [525485, 525486]
Group: 306, Nodes: [525487]
Group: 307, Nodes: [511076, 512081, 512267, 512228]
Group: 308, Nodes: [512268]
Group: 309, Nodes: [511077]
Group: 310, Nodes: [525489]
Group: 311, Nodes: [525490]
Group: 312, Nodes: [525488]
Group: 313, Nodes: [988307]
Group: 314, Nodes: [463980]
Group: 315, Nodes: [988306]
Group: 316, Nodes: [467922]
Group: 317, Nodes: [467873]
Group: 318, Nodes: [467920]
Group: 319, Nodes: [400460, 400460]
Group: 320, Nodes: [400470, 400470]
Group: 321, Nodes: [988399]
Group: 322, Nodes: [400810, 400810]
Group: 323, Nodes: [51034]
Group: 324, Nodes: [51035]
Group: 325, Nodes: [51117]
Group: 326, Nodes: [51115]
Group: 327, Nodes: [51131]
Group: 328, Nodes: [51130]
Group: 329, Nodes: [51033, 51112]
Group: 330, Nodes: [51056]
Group: 331, Nodes: [51124]
Group: 332, Nodes: [51123]
Group: 333, Nodes: [51125]
Group: 334, Nodes: [51043]
Group: 335, Nodes: [51040]
Group: 336, Nodes: [51129]
Group: 337, Nodes: [51126]
Group: 338, Nodes: [51110]
Group: 339, Nodes: [51055]
Group: 340, Nodes: [51114]
Group: 341, Nodes: [51042]
Group: 342, Nodes: [51203]
Group: 343, Nodes: [51120]
Group: 344, Nodes: [51121]
Group: 345, Nodes: [51122]
Group: 346, Nodes: [51167]
Group: 347, Nodes: [51135]
Group: 348, Nodes: [51163]
Group: 349, Nodes: [51134, 51053]
Group: 350, Nodes: [51166]
Group: 351, Nodes: [51150]
Group: 352, Nodes: [51050]
Group: 353, Nodes: [51015]
Group: 354, Nodes: [51143]
Group: 355, Nodes: [51024]
Group: 356, Nodes: [50111, 51152]
Group: 357, Nodes: [51164]
Group: 358, Nodes: [51148]
Group: 359, Nodes: [51147]
Group: 360, Nodes: [51141]
Group: 361, Nodes: [51111]
Group: 362, Nodes: [51105, 51039, 51104]
Group: 363, Nodes: [51144]
Group: 364, Nodes: [51146]
Group: 365, Nodes: [51151]
Group: 366, Nodes: [51138]
Group: 367, Nodes: [51145]
Group: 368, Nodes: [51101]
Group: 369, Nodes: [51025]
Group: 370, Nodes: [51023, 51103, 51182, 51022, 50202, 50202, 50202]
Group: 371, Nodes: [51100]
Group: 372, Nodes: [51161]
Group: 373, Nodes: [51109]
Group: 374, Nodes: [51108]
Group: 375, Nodes: [51175]
Group: 376, Nodes: [51128]
Group: 377, Nodes: [51027]
Group: 378, Nodes: [51026]
Group: 379, Nodes: [51133]
Group: 380, Nodes: [51132]
Group: 381, Nodes: [51127]
Group: 382, Nodes: [51028]
Group: 383, Nodes: [51019, 50011, 50011, 50011, 51106, 51018]
Group: 384, Nodes: [51020]
Group: 385, Nodes: [51107]
Group: 386, Nodes: [51171]
Group: 387, Nodes: [51181]
Group: 388, Nodes: [51180]
Group: 389, Nodes: [51185, 51021]
Group: 390, Nodes: [51014, 51013]
Group: 391, Nodes: [51016]
Group: 392, Nodes: [51186]
Group: 393, Nodes: [51187, 51189]
Group: 394, Nodes: [51188]
Group: 395, Nodes: [51172]
Group: 396, Nodes: [51170]
Group: 397, Nodes: [51178]
Group: 398, Nodes: [51179]
Group: 399, Nodes: [51177]
Group: 400, Nodes: [51155]
Group: 401, Nodes: [51156]
Group: 402, Nodes: [51160]
Group: 403, Nodes: [51048, 51157, 51136, 51142]
Group: 404, Nodes: [51158]
Group: 405, Nodes: [51049]
Group: 406, Nodes: [988331]
Group: 407, Nodes: [30025, 984890]
Group: 408, Nodes: [380050]
Group: 409, Nodes: [400169]
Group: 410, Nodes: [36287]
Group: 411, Nodes: [36482]
Group: 412, Nodes: [1018]
Group: 413, Nodes: [34000, 31508, 32001, 31609, 31609, 1017]
Group: 414, Nodes: [32002]
Group: 415, Nodes: [1021, 31616, 31616, 1020, 34082]
Group: 416, Nodes: [1022, 34084]
Group: 417, Nodes: [31501]
Group: 418, Nodes: [31504]
Group: 419, Nodes: [31505]
Group: 420, Nodes: [31503]
Group: 421, Nodes: [31502]
Group: 422, Nodes: [34083]
Group: 423, Nodes: [1019]
Group: 424, Nodes: [32004]
Group: 425, Nodes: [32005]
Group: 426, Nodes: [32003]
Group: 427, Nodes: [32006]
Group: 428, Nodes: [34059]
Group: 429, Nodes: [1016, 34005]
Group: 430, Nodes: [31991]
Group: 431, Nodes: [1014, 34006]
Group: 432, Nodes: [1015]
Group: 433, Nodes: [31992, 34010, 1003]
Group: 434, Nodes: [1002, 34011]
Group: 435, Nodes: [36263, 36264]
Group: 436, Nodes: [36261]
Group: 437, Nodes: [984885]
Group: 438, Nodes: [36243]
Group: 439, Nodes: [36253, 36255, 36250]
Group: 440, Nodes: [36629]
Group: 441, Nodes: [36621]
Group: 442, Nodes: [36236]
Group: 443, Nodes: [36239]
Group: 444, Nodes: [511203, 511258, 511258, 511130, 511130]
Group: 445, Nodes: [511163, 511163]
Group: 446, Nodes: [511132, 511132]
Group: 447, Nodes: [400343, 984883, 984883]
Group: 448, Nodes: [36230]
Group: 449, Nodes: [400644]
Group: 450, Nodes: [988338]
Group: 451, Nodes: [400681]
Group: 452, Nodes: [36493]
Group: 453, Nodes: [36495]
Group: 454, Nodes: [36575]
Group: 455, Nodes: [36580]
Group: 456, Nodes: [36273]
Group: 457, Nodes: [36563]
Group: 458, Nodes: [36278]
Group: 459, Nodes: [984889, 390513]
Group: 460, Nodes: [36588]
Group: 461, Nodes: [36285]
Group: 462, Nodes: [36283]
Group: 463, Nodes: [511138, 511138]
Group: 464, Nodes: [511139, 511139]
Group: 465, Nodes: [31597]
Group: 466, Nodes: [987294, 987294]
Group: 467, Nodes: [31598, 31598]
Group: 468, Nodes: [36608]
Group: 469, Nodes: [36606]
Group: 470, Nodes: [36592, 390287]
Group: 471, Nodes: [36594]
Group: 472, Nodes: [36596, 390202, 36598]
Group: 473, Nodes: [36847, 31633]
Group: 474, Nodes: [31640]
Group: 475, Nodes: [36822]
Group: 476, Nodes: [19000]
Group: 477, Nodes: [36825]
Group: 478, Nodes: [36819]
Group: 479, Nodes: [36840]
Group: 480, Nodes: [36841]
Group: 481, Nodes: [36843]
Group: 482, Nodes: [36978]
Group: 483, Nodes: [36974]
Group: 484, Nodes: [36976]
Group: 485, Nodes: [36979]
Group: 486, Nodes: [360268]
Group: 487, Nodes: [31634, 36985, 31634]
Group: 488, Nodes: [21062]
Group: 489, Nodes: [36967]
Group: 490, Nodes: [36972]
Group: 491, Nodes: [36835]
Group: 492, Nodes: [36838]
Group: 493, Nodes: [21099]
Group: 494, Nodes: [36829]
Group: 495, Nodes: [36831]
Group: 496, Nodes: [36827]
Group: 497, Nodes: [36496]
Group: 498, Nodes: [36504]
Group: 499, Nodes: [400684]
Group: 500, Nodes: [988342]
Group: 501, Nodes: [31622, 31622]
Group: 502, Nodes: [1008]
Group: 503, Nodes: [1009]
Group: 504, Nodes: [1010]
Group: 505, Nodes: [1005]
Group: 506, Nodes: [1007]
Group: 507, Nodes: [1004]
Group: 508, Nodes: [1012]
Group: 509, Nodes: [1013]
Group: 510, Nodes: [31611, 31611]
Group: 511, Nodes: [1011]
Group: 512, Nodes: [31610]
Group: 513, Nodes: [1029]
Group: 514, Nodes: [1030, 31603, 31603, 31603, 34089]
Group: 515, Nodes: [1028]
Group: 516, Nodes: [1025]
Group: 517, Nodes: [1026]
Group: 518, Nodes: [1027]
Group: 519, Nodes: [31506]
Group: 520, Nodes: [31605, 31605, 1024, 34085]
Group: 521, Nodes: [1023]
Group: 522, Nodes: [511008]
Group: 523, Nodes: [400530]
Group: 524, Nodes: [512003]
Group: 525, Nodes: [512062]
Group: 526, Nodes: [525244, 511009]
Group: 527, Nodes: [514034]
Group: 528, Nodes: [523017]
Group: 529, Nodes: [523018, 514033]
Group: 530, Nodes: [525236]
Group: 531, Nodes: [514035]
Group: 532, Nodes: [512063, 512064, 523016]
Group: 533, Nodes: [522008, 525246]
Group: 534, Nodes: [511010]
Group: 535, Nodes: [522007]
Group: 536, Nodes: [522009]
Group: 537, Nodes: [525245]
Group: 538, Nodes: [525247]
Group: 539, Nodes: [512005, 525234]
Group: 540, Nodes: [512007]
Group: 541, Nodes: [512006, 400070, 400070]
Group: 542, Nodes: [512061]
Group: 543, Nodes: [525235]
Group: 544, Nodes: [525233]
Group: 545, Nodes: [511006]
Group: 546, Nodes: [511007]
Group: 547, Nodes: [522011, 513032]
Group: 548, Nodes: [523022, 523022, 525573]
Group: 549, Nodes: [523012, 523012, 522012]
Group: 550, Nodes: [511039, 511266]
Group: 551, Nodes: [525571]
Group: 552, Nodes: [512065]
Group: 553, Nodes: [400550, 511038, 523015, 523015]
Group: 554, Nodes: [511265]
Group: 555, Nodes: [525572]
Group: 556, Nodes: [511268]
Group: 557, Nodes: [522010]
Group: 558, Nodes: [513023]
Group: 559, Nodes: [513031]
Group: 560, Nodes: [513030]
Group: 561, Nodes: [522027]
Group: 562, Nodes: [511267]
Group: 563, Nodes: [513024]
Group: 564, Nodes: [525321, 512039, 525322, 523026]
Group: 565, Nodes: [512067]
Group: 566, Nodes: [525320]
Group: 567, Nodes: [512056]
Group: 568, Nodes: [512040]
Group: 569, Nodes: [525323, 511256]
Group: 570, Nodes: [525319]
Group: 571, Nodes: [511254, 400060, 400060, 525318, 511253]
Group: 572, Nodes: [511262]
Group: 573, Nodes: [511255]
Group: 574, Nodes: [523021]
Group: 575, Nodes: [512041]
Group: 576, Nodes: [512057]
Group: 577, Nodes: [525324]
Group: 578, Nodes: [512059]
Group: 579, Nodes: [512058]
Group: 580, Nodes: [512042]
Group: 581, Nodes: [525317]
Group: 582, Nodes: [525316]
Group: 583, Nodes: [521066]
Group: 584, Nodes: [525315]
Group: 585, Nodes: [521064]
Group: 586, Nodes: [511251]
Group: 587, Nodes: [511250]
Group: 588, Nodes: [511252]
Group: 589, Nodes: [400018, 400018, 400018]
Group: 590, Nodes: [521063, 523019]
Group: 591, Nodes: [523020]
Group: 592, Nodes: [521062]
Group: 593, Nodes: [525241]
Group: 594, Nodes: [525242]
Group: 595, Nodes: [523006]
Group: 596, Nodes: [400090, 400090, 522006, 521023, 511013]
Group: 597, Nodes: [511014]
Group: 598, Nodes: [513015]
Group: 599, Nodes: [513016]
Group: 600, Nodes: [521022]
Group: 601, Nodes: [513019]
Group: 602, Nodes: [513017]
Group: 603, Nodes: [523004]
Group: 604, Nodes: [512028]
Group: 605, Nodes: [512027]
Group: 606, Nodes: [512045]
Group: 607, Nodes: [512031]
Group: 608, Nodes: [512032, 521055, 512033, 512034]
Group: 609, Nodes: [512030, 523003]
Group: 610, Nodes: [512029]
Group: 611, Nodes: [512047]
Group: 612, Nodes: [525240, 523005, 512049]
Group: 613, Nodes: [512048]
Group: 614, Nodes: [512046]
Group: 615, Nodes: [512055, 512026, 400421, 521060]
Group: 616, Nodes: [512023]
Group: 617, Nodes: [512024]
Group: 618, Nodes: [521058]
Group: 619, Nodes: [512025]
Group: 620, Nodes: [513014, 521021, 400110, 400110]
Group: 621, Nodes: [521061]
Group: 622, Nodes: [525092]
Group: 623, Nodes: [511269]
Group: 624, Nodes: [511270]
Group: 625, Nodes: [525248, 513020]
Group: 626, Nodes: [513018]
Group: 627, Nodes: [525243]
Group: 628, Nodes: [513021]
Group: 629, Nodes: [513022]
Group: 630, Nodes: [512051]
Group: 631, Nodes: [512050]
Group: 632, Nodes: [511271, 512052]
Group: 633, Nodes: [525239]
Group: 634, Nodes: [512071]
Group: 635, Nodes: [512013]
Group: 636, Nodes: [513005]
Group: 637, Nodes: [521025]
Group: 638, Nodes: [521024, 513001, 400080, 400080, 511012]
Group: 639, Nodes: [521026]
Group: 640, Nodes: [513003]
Group: 641, Nodes: [512015]
Group: 642, Nodes: [512016, 513004]
Group: 643, Nodes: [511011]
Group: 644, Nodes: [512044]
Group: 645, Nodes: [512054]
Group: 646, Nodes: [512043]
Group: 647, Nodes: [512060]
Group: 648, Nodes: [512068]
Group: 649, Nodes: [512011]
Group: 650, Nodes: [512010]
Group: 651, Nodes: [512009]
Group: 652, Nodes: [512008, 521028]
Group: 653, Nodes: [521027]
Group: 654, Nodes: [522004]
Group: 655, Nodes: [513006]
Group: 656, Nodes: [513007]
Group: 657, Nodes: [511016, 513002, 513011]
Group: 658, Nodes: [513010]
Group: 659, Nodes: [513009, 522003]
Group: 660, Nodes: [513008]
Group: 661, Nodes: [512018]
Group: 662, Nodes: [522005, 511015, 512020]
Group: 663, Nodes: [512017]
Group: 664, Nodes: [512022, 513012]
Group: 665, Nodes: [513013]
Group: 666, Nodes: [190170, 230777, 525516, 525578, 511001]

In [26]:
for k in list(suspected_nodes.keys()):
  if len(suspected_nodes[k]) == 0:
    suspected_nodes.pop(k)

In [28]:
for k in suspected_nodes.keys():
  suspected_nodes[k] = set(suspected_nodes[k])

In [29]:
suspected_nodes

{np.int64(10): {31656},
 np.int64(17): {30003, 36903},
 np.int64(21): {31624},
 np.int64(27): {36907, 36909},
 np.int64(38): {36964, 36965},
 np.int64(73): {31525},
 np.int64(90): {34063, 34064, 36858, 36860, 36862},
 np.int64(106): {463640},
 np.int64(111): {463642},
 np.int64(164): {500093, 500094},
 np.int64(189): {500073, 500212},
 np.int64(193): {400841},
 np.int64(244): {400820, 500042, 500222},
 np.int64(271): {512132, 512185},
 np.int64(276): {400380},
 np.int64(277): {511070, 511088, 511089, 512121, 512122},
 np.int64(280): {511086, 511087, 512195, 512270, 525477, 525478},
 np.int64(301): {400360, 511051, 511055, 511099, 511100},
 np.int64(302): {511097, 511098, 512237, 512238},
 np.int64(307): {512081, 512267},
 np.int64(319): {400460},
 np.int64(320): {400470},
 np.int64(322): {400810},
 np.int64(370): {50202, 51022, 51023, 51182},
 np.int64(383): {50011, 51018, 51019},
 np.int64(403): {51136, 51142},
 np.int64(413): {31609},
 np.int64(415): {31616},
 np.int64(444): {511130, 511258},
 np.int64(445): {511163},
 np.int64(446): {511132},
 np.int64(447): {984883},
 np.int64(463): {511138},
 np.int64(464): {511139},
 np.int64(466): {987294},
 np.int64(467): {31598},
 np.int64(472): {36596, 390202},
 np.int64(487): {31634},
 np.int64(501): {31622},
 np.int64(510): {31611},
 np.int64(514): {31603},
 np.int64(520): {31605},
 np.int64(532): {512063, 512064},
 np.int64(541): {400070},
 np.int64(548): {523022},
 np.int64(549): {523012},
 np.int64(553): {523015},
 np.int64(564): {525321, 525322},
 np.int64(571): {400060, 511253, 511254},
 np.int64(589): {400018},
 np.int64(596): {400090},
 np.int64(608): {512032, 512033},
 np.int64(615): {512026, 512055},
 np.int64(620): {400110},
 np.int64(638): {400080},
 np.int64(657): {513002, 513011},
 np.int64(666): {230777, 525578},
 np.int64(677): {523014},
 np.int64(690): {521068},
 np.int64(691): {521069},
 np.int64(695): {525308, 525309},
 np.int64(700): {521067},
 np.int64(708): {521070},
 np.int64(709): {525203},
 np.int64(710): {521071},
 np.int64(715): {521039, 525060},
 np.int64(717): {523010},
 np.int64(723): {523024},
 np.int64(724): {523025},
 np.int64(725): {400402},
 np.int64(731): {523023},
 np.int64(737): {400415},
 np.int64(738): {511232},
 np.int64(742): {511239},
 np.int64(743): {511240, 511241},
 np.int64(747): {511243},
 np.int64(748): {511221},
 np.int64(752): {511204, 511237},
 np.int64(753): {400020},
 np.int64(754): {511259, 511260},
 np.int64(756): {511238},
 np.int64(760): {511129},
 np.int64(764): {511224, 511225, 511226, 511227, 511228},
 np.int64(765): {511229, 511230},
 np.int64(772): {511210, 511257},
 np.int64(799): {516008, 516009},
 np.int64(806): {150620, 515022, 515049, 516022, 516023},
 np.int64(846): {512241, 512249},
 np.int64(878): {511153},
 np.int64(879): {511152},
 np.int64(880): {511263},
 np.int64(882): {511148},
 np.int64(884): {511133},
 np.int64(885): {511135},
 np.int64(919): {511155},
 np.int64(920): {511159},
 np.int64(924): {511143},
 np.int64(926): {511144},
 np.int64(927): {511142},
 np.int64(928): {511146},
 np.int64(940): {400013},
 np.int64(942): {516039, 525559},
 np.int64(954): {515018, 515026, 516025, 516026},
 np.int64(959): {515004, 515073},
 np.int64(960): {515005, 515006},
 np.int64(968): {525493, 525494},
 np.int64(971): {511066, 511072},
 np.int64(980): {511068, 511075, 512110, 512232},
 np.int64(988): {400350},
 np.int64(990): {400012},
 np.int64(992): {521078},
 np.int64(993): {515070, 515078},
 np.int64(997): {521043},
 np.int64(1003): {400320},
 np.int64(1005): {400410, 521045},
 np.int64(1011): {515037, 515072, 521044},
 np.int64(1012): {400441}}

In [31]:
df[df['group']==10]

,h3_index,node,Mode_Planned,Line_Nunique,Line_Unique,LandOwnership,Region,Location,Boardings_Daily,Alightings_Daily,TotalDemand_Daily,geometry,group,address
Column1,,,,,,,,,,,,,,
11,8a2da4c3119ffff,31656,HighSpeed Rail,4,['rail_5_1' 'rail_5_2' 'rail_1_1' 'rail_1_2'],State,Haifa,Outer,7780.030957,3011.574279,10791.60524,POLYGON ((35.295481553874545 32.92421827542802...,10,"דרור, מגדים, כרמיאל, נפת עכו, מחוז הצפון, 2196..."
12,8a2da4c3119ffff,31656,Suburban Rail,2,['rail_6_1' 'rail_6_2'],State,Haifa,Outer,7780.030957,3011.574279,10791.60524,POLYGON ((35.295481553874545 32.92421827542802...,10,"דרור, מגדים, כרמיאל, נפת עכו, מחוז הצפון, 2196..."

In [32]:
nodes_df = pd.DataFrame.from_dict(suspected_nodes, orient='index')

In [34]:
nodes_df.to_csv('/content/suspected_nodes.csv')