In [ ]:
import pandas as pd
import numpy as np
import geopandas as gpd

import os

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Hubs/grouped_hubs_for_filtering_29102025.csv', encoding='utf-8')

In [ ]:
df.head(1)

,group,geometry,h3_index,node,Mode_Planned,Model,Line_Unique,address,area,location,...,Suburban Rail Lines,centroid,pop_0_500,emp_0_500,pop_500_1000,emp_500_1000,pop_1000_1500,emp_1000_1500,id,term_type
0,0,"POLYGON ((35.58265301880704 33.2100839260914, ...",['8a2da4100a27fff'],['31655'],['Interurban Rail'],['National'],"[""['rail_1_1' 'rail_1_2']""]","מנחם בגין/נורית, שדרות מנחם בגין, הורדים, קרית...",['צפון'],['צפון'],...,0,POINT (35.582038147824136 33.21058342039613),1740.269399,419.036219,5285.782076,2114.166257,8147.750386,5330.187199,928.0,חניון לילה

In [ ]:
df[df['group']==955]#[['TotalDemand']]

,group,geometry,h3_index,node,Mode_Planned,Model,Line_Unique,address,area,location,...,Suburban Rail Lines,centroid,pop_0_500,emp_0_500,pop_500_1000,emp_500_1000,pop_1000_1500,emp_1000_1500,id,term_type
959,955,MULTIPOLYGON (((34.77596964028979 31.887242985...,"['8a3f4dd9a14ffff', '8a3f4dd9a14ffff', '8a3f4d...","['511075', '511075', '512110', '511068', '5122...",['LRT'],"['Tel Aviv', 'Ashdod-ashkelon']","[""['L1-N' 'L1-S']"", ""['Light-Blue_S' 'Turquois...","מועצה אזורית גן רווה, נפת רחובות, מחוז המרכז, ...",['תל אביב'],"['טבעת חיצונית', 'טבעת תיכונה']",...,0,POINT (34.778608391982594 31.888777676526423),4221.632603,968.594837,12896.506554,3521.029844,14759.735135,4443.756561,899.0,חניון לילה

In [ ]:
df.columns

Index(['group', 'geometry', 'h3_index', 'node', 'Mode_Planned', 'Model',
       'Line_Unique', 'address', 'area', 'location', 'TotalDemand',
       'TotalTransfers', 'Total_Unique_Lines', 'BRT Lines', 'Cable Line Lines',
       'Funicular Lines', 'HighSpeed Rail Lines', 'Interurban Rail Lines',
       'LRT Lines', 'Metro Lines', 'Suburban Rail Lines', 'centroid',
       'pop_0_500', 'emp_0_500', 'pop_500_1000', 'emp_500_1000',
       'pop_1000_1500', 'emp_1000_1500', 'id', 'term_type'],
      dtype='object')

## Convert Line_Unique and Mode_Planned to a list of lines

In [ ]:
def split_lines(txt):
  txt = txt.replace("'","").replace("[","").replace("]","").replace("\"","").split(" ")

  return txt

In [ ]:
df['Line_Unique'] = df['Line_Unique'].apply(lambda x: split_lines(x))

In [ ]:
df['Mode_Planned'] = df['Mode_Planned'].apply(lambda x: split_lines(x))

## Convert node column to a list of nodes

In [ ]:
[int(x) for x in df['node'][0].replace("'","").replace("[","").replace("]","").replace("\"","").split(" ")]

[31655]

In [ ]:
def node_list(txt):
  txt = [int(x) for x in txt.replace("'","").replace("[","").replace("]","").replace("\"","").replace(',',"").split(" ")]

  return txt

In [ ]:
df['node'] = df['node'].apply(lambda x: node_list(x))

## Convert h3_index column to a list of h3_indices

In [ ]:
def h3_index_list(txt):
  txt =  txt.replace("'","").replace("[","").replace("]","").replace("\"","").replace(',',"").split(" ")

  return txt

In [ ]:
df['h3_index'] = df['h3_index'].apply(lambda x: h3_index_list(x))

## Convert text columns: Model, Location, Area to a single value text

In [ ]:
def single_value(txt):
  txt = txt.replace("'","").replace("[","").replace("]","").replace("\"","").replace(",","").split(" ")[0]

  return txt

In [ ]:
df['Model'] = df['Model'].apply(lambda x: single_value(x))
df['location'] = df['location'].apply(lambda x: single_value(x))
df['area'] = df['area'].apply(lambda x: single_value(x))

## Result

In [ ]:
df.head(1)

,group,geometry,h3_index,node,Mode_Planned,Model,Line_Unique,address,area,location,...,Suburban Rail Lines,centroid,pop_0_500,emp_0_500,pop_500_1000,emp_500_1000,pop_1000_1500,emp_1000_1500,id,term_type
0,0,"POLYGON ((35.58265301880704 33.2100839260914, ...",[8a2da4100a27fff],[31655],"[Interurban, Rail]",National,"[rail_1_1, rail_1_2]","מנחם בגין/נורית, שדרות מנחם בגין, הורדים, קרית...",צפון,צפון,...,0,POINT (35.582038147824136 33.21058342039613),1740.269399,419.036219,5285.782076,2114.166257,8147.750386,5330.187199,928.0,חניון לילה

In [ ]:
# Save result to reduce future run time
df.to_csv('/content/drive/MyDrive/Hubs/grouped_hubs_converted_ready_for_filtering_and_scoring_29102025.csv', encoding='utf-8')

# Categorize the different criteria columns (convert text to a numerical category)

### Region/Area

In [ ]:
df['area'].unique()

array(['צפון', 'חיפה', 'דרום', 'באר', 'תל', 'ירושלים', ''], dtype=object)

In [ ]:
# correct values spelling
def correct_area(txt):
  if txt == 'תל':
    return 'תל אביב'
  elif txt == 'באר':
    return 'באר שבע'
  else:
    return txt

In [ ]:
df['area'] = df['area'].apply(lambda x: correct_area(x))

In [ ]:
df['area'].unique()

array(['צפון', 'חיפה', 'דרום', 'באר שבע', 'תל אביב', 'ירושלים', ''],
      dtype=object)

In [ ]:
d = {k:1 for k in df['area'].unique() if k not in ['תל אביב','nan']}
d['תל אביב'] = 0
d['nan'] = 0

In [ ]:
def get_area_category(x) -> int:
  return d[x]

In [ ]:
df['Region_category'] = df['area'].apply(lambda x: get_area_category(x))

In [ ]:
df['Region_category'].head(5)

0    1
1    1
2    1
3    1
4    1
Name: Region_category, dtype: int64

### Location

In [ ]:
df['location'].unique()

array(['צפון', 'טבעת', 'דרום', 'גלעין', 'חיפה', ''], dtype=object)

In [ ]:
def get_location_category(x) -> int:
  l = {'חיפה': 1,
       'צפון': 1,
       'דרום': 1,
       'טבעת': 2,
       'גלעין': 3,
       'nan': 1,
       '': 1}

  return l[x]

In [ ]:
df['Location_category'] = df['location'].apply(lambda x: get_location_category(x))

In [ ]:
df['Location_category'].unique()

array([1, 2, 3])

### Region*Location

In [ ]:
df['RegionLocation'] = df['Region_category'] * df['Location_category']

### Mode score

In [ ]:
df.columns

Index(['group', 'geometry', 'h3_index', 'node', 'Mode_Planned', 'Model',
       'Line_Unique', 'address', 'area', 'location', 'TotalDemand',
       'TotalTransfers', 'Total_Unique_Lines', 'BRT Lines', 'Cable Line Lines',
       'Funicular Lines', 'HighSpeed Rail Lines', 'Interurban Rail Lines',
       'LRT Lines', 'Metro Lines', 'Suburban Rail Lines', 'centroid',
       'pop_0_500', 'emp_0_500', 'pop_500_1000', 'emp_500_1000',
       'pop_1000_1500', 'emp_1000_1500', 'id', 'term_type', 'Region_category',
       'Location_category', 'RegionLocation'],
      dtype='object')

In [ ]:
mode_weights = {
    'Funicular': 1,
    'Cable Line': 2,
    'BRT': 3,
    'LRT': 4,
    'Metro': 5,
    'Suburban Rail': 6,
    'Interurban Rail': 7,
    'HighSpeed Rail': 8
}

In [ ]:
def count_positive_mode_lines(row):
  count = 0
  mode_line_cols = ['BRT Lines', 'Cable Line Lines', 'Funicular Lines',
                    'HighSpeed Rail Lines', 'Interurban Rail Lines', 'LRT Lines',
                    'Metro Lines', 'Suburban Rail Lines']
  for col in mode_line_cols:
    if col in row.index and row[col] > 0:
      count += 1
  return count

In [ ]:
df['Num_Modes'] = df.apply(count_positive_mode_lines, axis=1)

In [ ]:
def get_mode_score(row):
  score = 0
  # for deminishing return
  alpha = 0.1
  for mode, weight in mode_weights.items():
    # Check if the mode exists in the Mode_Planned list
    if mode in row['Mode_Planned']:
      # Construct the column name
      column_name = f'{mode} Lines'
      # Check if the column exists in the DataFrame
      if column_name in row.index:
        score += row[column_name] * weight
  score = score * (1 + alpha * (row['Num_Modes'] - 1))
  return score

In [ ]:
# problem with Mode_Planned lists
# remove 'Rail', add ' Rail' to HighSpeed, Interurban, Suburban
# remove , from strings
def correct_mode_planned(x):
  if ('Rail' in x) or (' Rail' in x):
    x.remove('Rail')
  if 'HighSpeed' in x:
    x.append('HighSpeed Rail')
    x.remove('HighSpeed')
  if 'Interurban' in x:
    x.append('Interurban Rail')
    x.remove('Interurban')
  if 'Suburban' in x:
    x.append('Suburban Rail')
    x.remove('Suburban')

  for i in range(len(x)):
    x[i] = x[i].replace(',','')

  return x

In [ ]:
df['Mode_Planned'] = df['Mode_Planned'].apply(lambda x: correct_mode_planned(x))

In [ ]:
df['score'] = df.apply(get_mode_score, axis=1)

In [ ]:
df[df.index==8]['Mode_Planned'].values[0]

['Rail', 'Interurban Rail', 'Suburban Rail']

In [ ]:
df[df['Num_Modes']>1][['Mode_Planned','Num_Modes','BRT Lines', 'Cable Line Lines', 'Funicular Lines',
       'HighSpeed Rail Lines', 'Interurban Rail Lines', 'LRT Lines',
       'Metro Lines', 'Suburban Rail Lines','score']]

,Mode_Planned,Num_Modes,BRT Lines,Cable Line Lines,Funicular Lines,HighSpeed Rail Lines,Interurban Rail Lines,LRT Lines,Metro Lines,Suburban Rail Lines,score
8,"[Rail, Interurban Rail, Suburban Rail]",2,0,0,0,0,4,0,0,2,44.0
16,"[Rail, HighSpeed Rail, Interurban Rail]",2,0,0,0,2,2,0,0,0,33.0
33,"[BRT, LRT]",2,12,0,0,0,0,3,0,0,52.8
58,"[LRT, BRT]",2,12,0,0,0,0,1,0,0,44.0
59,"[BRT, LRT]",2,6,0,0,0,0,12,0,0,72.6
...,...,...,...,...,...,...,...,...,...,...,...
985,"[Rail, Interurban Rail, Suburban Rail]",2,0,0,0,0,6,0,0,8,99.0
987,"[BRT, Rail, Rail, LRT, Interurban Rail, Suburb...",4,6,0,0,0,4,2,0,4,101.4
988,"[Rail, BRT, Interurban Rail]",2,2,0,0,0,2,0,0,0,22.0
993,"[BRT, LRT]",2,10,0,0,0,0,2,0,0,41.8
994,"[Rail, Interurban Rail, Suburban Rail]",2,0,0,0,0,4,0,0,4,57.2

### Bus Terminal proximity
if bus terminal type is 'מסוף קטן' or 'מסוף בינוני' then value is 1 <br>
if type is 'מסוף גדול' or 'מתקן משולב' then value is 2
else: 0

In [ ]:
df['term_type'].unique()

array(['חניון לילה', nan, 'מסוף בינוני', 'מסוף קטן', 'מתקן משולב',
       'מסוף גדול'], dtype=object)

In [ ]:
def bus_terminal(x) -> int:
  if x == 'חניון לילה':
    return 1
  elif x == 'מסוף קטן' or x == 'מסוף בינוני':
    return 2
  elif x == 'מסוף גדול' or x == 'מתקן משולב':
    return 3
  else:
    return 0

In [ ]:
df['bus_terminal'] = df['term_type'].apply(lambda x: bus_terminal(x))

In [ ]:
df['bus_terminal']

0       1
1       0
2       0
3       0
4       0
       ..
1012    0
1013    0
1014    0
1015    0
1016    0
Name: bus_terminal, Length: 1017, dtype: int64

### Pop, Emp 2050
no action required at the moment <br>
scoring will be weight-based according to the ring <br>
will be done at the scoring phase (another notebook)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017 entries, 0 to 1016
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   group                  1017 non-null   int64
 1   geometry               1017 non-null   object
 2   h3_index               1017 non-null   object
 3   node                   1017 non-null   object
 4   Mode_Planned           1017 non-null   object
 5   Model                  1017 non-null   object
 6   Line_Unique            1017 non-null   object
 7   address                1017 non-null   object
 8   area                   1017 non-null   object
 9   location               1017 non-null   object
 10  TotalDemand            1017 non-null   float64
 11  TotalTransfers         1017 non-null   float64
 12  Total_Unique_Lines     1017 non-null   int64
 13  BRT Lines              1017 non-null   int64
 14  Cable Line Lines       1017 non-null   int64
 15  Funicular Lines        1017 non-null   int64
 16  HighSpeed Rail Lines   1017 non-null   int64
 17  Interurban Rail Lines  1017 non-null   int64
 18  LRT Lines              1017 non-null   int64
 19  Metro Lines            1017 non-null   int64
 20  Suburban Rail Lines    1017 non-null   int64
 21  centroid               1017 non-null   object
 22  pop_0_500              1017 non-null   float64
 23  emp_0_500              1017 non-null   float64
 24  pop_500_1000           1017 non-null   float64
 25  emp_500_1000           1017 non-null   float64
 26  pop_1000_1500          1017 non-null   float64
 27  emp_1000_1500          1017 non-null   float64
 28  id                     163 non-null    float64
 29  term_type              163 non-null    object
 30  Region_category        1017 non-null   int64
 31  Location_category      1017 non-null   int64
 32  RegionLocation         1017 non-null   int64
 33  Num_Modes              1017 non-null   int64
 34  score                  1017 non-null   float64
 35  bus_terminal           1017 non-null   int64
dtypes: float64(10), int64(15), object(11)
memory usage: 286.2+ KB

### Set Hub type

In [ ]:
def set_hub_type(df, cols):
  total_daily_demand = cols[0]
  service_types = cols[1]
  num_lines = len(cols[2]) # Get the length of the Line_Unique list

  # if has HighSpeed Rail or Interurban Rail, and Line Nunique is at least 3, Then it is a National type
  # if has Suburban Rail or Metro, and Line Nunique is at least 3, then it is a Regional type
  # if has BRT or LRT, Line Nunique is a least 3 and demand is greater then 10000, then it is a Local type
  # if has any Rail but Line Nunique is up to 2 or has less than 10000 daily demand, than it is Train Station
  # else - not hub
  if (('Interurban Rail' in service_types) or ('HighSpeed Rail' in service_types)) and (num_lines >= 3) and (total_daily_demand>=50000):
    return 'National'
  elif (('Suburban Rail' in service_types) or ('Metro' in service_types) or ('Interurban Rail' in service_types) or ('HighSpeed Rail' in service_types)) and (num_lines >= 3):
    return 'Regional'
  elif (('BRT' in service_types) or ('LRT' in service_types)) and (num_lines >= 3) and (total_daily_demand >= 1000):
    return 'Local'
  elif (('Interurban Rail' in service_types) or ('HighSpeed Rail' in service_types) or ('Suburban Rail' in service_types)) and (num_lines <= 2):
    return 'Train Station'
  else:
    return 'Not Hub'

In [ ]:
df.columns

Index(['group', 'geometry', 'h3_index', 'node', 'Mode_Planned', 'Model',
       'Line_Unique', 'address', 'area', 'location', 'TotalDemand',
       'TotalTransfers', 'Total_Unique_Lines', 'BRT Lines', 'Cable Line Lines',
       'Funicular Lines', 'HighSpeed Rail Lines', 'Interurban Rail Lines',
       'LRT Lines', 'Metro Lines', 'Suburban Rail Lines', 'centroid',
       'pop_0_500', 'emp_0_500', 'pop_500_1000', 'emp_500_1000',
       'pop_1000_1500', 'emp_1000_1500', 'id', 'term_type', 'Region_category',
       'Location_category', 'RegionLocation', 'Num_Modes', 'score',
       'bus_terminal'],
      dtype='object')

In [ ]:
df['HubType'] = df[['TotalDemand', 'Mode_Planned', 'Line_Unique']].apply(lambda x: set_hub_type(df, x), axis=1)

/tmp/ipython-input-3367051631.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  total_daily_demand = cols[0]
/tmp/ipython-input-3367051631.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  service_types = cols[1]
/tmp/ipython-input-3367051631.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num_lines = len(cols[2]) # Get the length of the Line_Unique list

In [ ]:
df.head()

,group,geometry,h3_index,node,Mode_Planned,Model,Line_Unique,address,area,location,...,emp_1000_1500,id,term_type,Region_category,Location_category,RegionLocation,Num_Modes,score,bus_terminal,HubType
0,0,"POLYGON ((35.58265301880704 33.2100839260914, ...",[8a2da4100a27fff],[31655],[Interurban Rail],National,"[rail_1_1, rail_1_2]","מנחם בגין/נורית, שדרות מנחם בגין, הורדים, קרית...",צפון,צפון,...,5330.187199,928.0,חניון לילה,1,1,1,1,14.0,1,Train Station
1,1,"POLYGON ((35.32671223620188 32.92554871232436,...",[8a2da4c22257fff],[36963],[BRT],Haifa,[brt022],"מיי סנטר, מעלה כמון, אזור תעשייה כרמיאל, אזור ...",צפון,צפון,...,9064.998488,NaN,NaN,1,1,1,1,3.0,0,Not Hub
2,2,MULTIPOLYGON (((35.31637847673026 32.921966033...,"[8a2da4c22627fff, 8a2da4c2275ffff]","[36959, 36961]",[BRT],Haifa,"[brt021, brt022,, brt021]","החרושת/חשמל, החרושת, אזור תעשייה כרמיאל, מרכז ...",צפון,צפון,...,8282.264877,NaN,NaN,1,1,1,1,9.0,0,Not Hub
3,3,"POLYGON ((35.34684915390923 32.86202464664849,...",[8a2da4c24987fff],[36924],[BRT],Haifa,"[brt011, brt012, brt021, brt022]","طريق الجليل, عرابة, נפת עכו, מחוז הצפון, 20176...",צפון,צפון,...,2865.147509,NaN,NaN,1,1,1,1,12.0,0,Not Hub
4,4,"POLYGON ((35.2815307559088 32.910659675497065,...",[8a2da4c30057fff],[36935],[BRT],Haifa,"[brt021, brt022]","בי""ס מקיף אורט כרמים, מעלה אורט, הגליל, רמת רב...",צפון,צפון,...,4477.250200,NaN,NaN,1,1,1,1,6.0,0,Not Hub

In [ ]:
df.to_csv('/content/drive/MyDrive/Hubs/grouped_hubs_ready_for_scoring_29102025.csv', encoding='utf-8')